### ISSUE TITLE
[Bug] 1.3.0 upgrade: 2400AC not charging any more, many errors logged

### ISSUE THREAD

**Issue by ahocevar** [Zendure/Zendure-HA#1302]
### Home Assistant Version

2026.4.4

### Zendure Integration Version

v1.3.0

### Describe the bug

After the 1.3.0 update, my SolarFlow 2400 AC does not charge any more, even if my two Hyper 2000 produce enough power. Maybe it's related to these two errors that are logged multiple times every minute:

### To Reproduce

When updating from a working pre-1.3.0 system to 1.3.0, the above error messages start appearing, and 2400AC does not get charged with the excess power from the two Hyper 2000 any more.

See log extracts below

### Expected Behaviour

* 2400AC gets charged with the excess power from the two Hyper 2000.
* The new errors which get logged every couple of seconds disappear atain.

### What device are you using?

SF2400 AC

### Log Extracts

```shell
Logger: custom_components.zendure_ha.manager
Source: custom_components/zendure_ha/manager.py:414
integration: Zendure Home Assistant Integration ([documentation](https://github.com/zendure/zendure-ha), [issues](https://github.com/zendure/zendure-ha/issues))
First occurred: 12:41:53 PM (33 occurrences)
Last logged: 12:47:07 PM

'ZendureNumber' object has no attribute 'asInt'



Logger: custom_components.zendure_ha.manager
Source: custom_components/zendure_ha/manager.py:415
integration: Zendure Home Assistant Integration ([documentation](https://github.com/zendure/zendure-ha), [issues](https://github.com/zendure/zendure-ha/issues))
First occurred: 12:41:53 PM (33 occurrences)
Last logged: 12:47:07 PM

Traceback (most recent call last): File "/config/custom_components/zendure_ha/manager.py", line 412, in _p1_changed await self.powerChanged(p1, isFast, time) File "/config/custom_components/zendure_ha/manager.py", line 475, in powerChanged await self.power_charge(setpoint, time) File "/config/custom_components/zendure_ha/manager.py", line 565, in power_charge await d.power_charge(-start_pwr - max(0, d.pwr_offgrid) if d.state != DeviceState.SOCFULL else -max(0, d.pwr_offgrid)) File "/config/custom_components/zendure_ha/device.py", line 620, in power_charge return await self.charge(power) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/zendure_ha/device.py", line 741, in charge if power == -SmartMode.POWER_START and self.limitInput.asInt == -SmartMode.POWER_START and self.homeInput.asInt == 0: ^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'ZendureNumber' object has no attribute 'asInt'
```

**Comment by FireSon** [comment]
@ahocevar  thanks for the report, please check out version 1.3.1 There is already other issue #1301 about the same problem.

**Comment by ahocevar** [comment]
Thanks @FireSon for publishing a new release so quickly! The logged errors are gone, but the behavior of the 2400AC is still not right: it changes between charging and discharging every minute or so, although there is still enough excess power from the two Hyper 2000. This is an excerpt from the activity log:
```
AB3000 00683 State  changed to Charging
5:03:55 PM - 1 minute ago

AB3000 02855 State  changed to Charging
5:03:55 PM - 1 minute ago

AB3000 01361 State  changed to Charging
5:03:55 PM - 1 minute ago

SolarFlow 2400 AC Battery State  changed to Charging
5:03:55 PM - 1 minute ago

SolarFlow 2400 AC AC Input Limit  changed to 60.0
5:03:50 PM - 1 minute ago

Zendure Manager Operation State  changed to Charging
5:03:45 PM - 1 minute ago

SolarFlow 2400 AC Bypass  changed to Off
5:02:50 PM - 2 minutes ago

SolarFlow 2400 AC AC Operation Mode  changed to AC Input Mode
5:02:45 PM - 2 minutes ago

SolarFlow 2400 AC Battery State  changed to Discharging
5:02:35 PM - 2 minutes ago

AB3000 00683 State  changed to Discharging
5:02:30 PM - 2 minutes ago

AB3000 02855 State  changed to Discharging
5:02:30 PM - 2 minutes ago

AB3000 01361 State  changed to Discharging
5:02:30 PM - 2 minutes ago

SolarFlow 2400 AC AC Input Limit  changed to 0.0
5:02:30 PM - 2 minutes ago

SolarFlow 2400 AC AC Operation Mode  changed to AC Output Mode
5:02:30 PM - 2 minutes ago

SolarFlow 2400 AC Bypass  changed to 3
5:02:30 PM - 2 minutes ago

Zendure Manager Operation State  changed to Idle
5:02:24 PM - 3 minutes ago

SolarFlow 2400 AC AC Input Limit  changed to 393.0
5:02:24 PM - 2 minutes ago

SolarFlow 2400 AC AC Input Limit  changed to 362.0
5:02:20 PM - 2 minutes ago

SolarFlow 2400 AC AC Input Limit  changed to 298.0
5:02:14 PM - 2 minutes ago

AB3000 00683 State  changed to Charging
5:02:05 PM - 2 minutes ago

AB3000 02855 State  changed to Charging
5:02:00 PM - 3 minutes ago

AB3000 01361 State  changed to Charging
5:02:00 PM - 3 minutes ago

SolarFlow 2400 AC AC Input Limit  changed to 60.0
5:02:00 PM - 3 minutes ago

SolarFlow 2400 AC Battery State  changed to Charging
5:02:00 PM - 3 minutes ago
```
So it seems the Zendure Manager switches to idle the moment the 2400 AC starts taking significant charge, and then the cycle starts again.
