### ISSUE TITLE
[Bug] Solarflow 2400AC batteries become inactive few minutes after home assistant restart

### ISSUE THREAD

**Issue by HomeAssistantPim** [Zendure/Zendure-HA#1622]
### Home Assistant Version

2026.7.2

### Zendure Integration Version

v1.4.4

### Describe the bug

I was calibrating the solarflow 2400AC by charging it at 1500W until it's full and discharge it after some hours (having issues as of a few weeks).
But the manual charge did not complete due to a restart of HA at 5:00
5 minutes after restart the batteries become inactive and no longer responded.
I tried to set it to charge again around 9:00, but the charge limit dropped back to 100W and the batteries were inactive.
In this state I did manage to do a firmware upgrade via the zendure app, after succesfull upgrade I needed to reboot the solarflow (via the app it also did not respond anymore reporting the solarflow was not connected to the cloud).
After reboot I could set it to charge at 1500W again, this went fine for a while untill I issued a restart of HA.
Few minutes after restart the batteries became inactive again.
I could however reissue the charge at 1500W and it responded (I guess I was quick enough this time?).

Why is it that after restart the integration messes with my solarflow, such that it become inactive?

P.s. my setup communicates via the cloud as I wasn't able to get it to work with MQTT yet.

### To Reproduce

1. Set to manually charge
2. Reboot HA
3. See that after restart the charge power may change a bit (at least I've seen it)
4. See that after a few minutes the batteries suddenly become inactive 

### Expected Behaviour

Solarflow should stick with it's setting even during/after restarts

### What device are you using?

SF2400 AC

### Log Extracts

```shell
[31m2026-08-26 02:49:14.153 ERROR (MainThread) [homeassistant.components.airthings_ble.coordinator] Error fetching airthings_ble data: Unable to fetch data: Disconnected from 74:D2:85:05:8A:70[0m
[31m2026-08-26 03:59:07.657 ERROR (MainThread) [custom_components.tplink_deco.api] List Devices connection error: Cannot connect to host tplinkdeco.net:443 ssl:<ssl.SSLContext object at 0xffff89156f30> [None][0m
[31m2026-08-26 03:59:07.658 ERROR (MainThread) [custom_components.tplink_deco.coordinator] Error requesting tplink_deco-decos data: Cannot connect to host tplinkdeco.net:443 ssl:<ssl.SSLContext object at 0xffff89156f30> [None][0m
[31m2026-08-26 04:59:25.190 ERROR (MainThread) [homeassistant.components.airthings_ble.coordinator] Error fetching airthings_ble data: Unable to fetch data: Disconnected from 74:D2:85:05:8A:70[0m
[33m2026-08-26 05:00:01.846 WARNING (MainThread) [bleak.backends.bluezdbus.client] Failed to cancel connection (/org/bluez/hci0/dev_74_D2_85_05_8A_70): [org.freedesktop.DBus.Error.NameHasNoOwner] Could not activate remote peer 'org.bluez': activation request failed: unit is invalid[0m
[31m2026-08-26 05:00:08.224 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:False [Connect call failed ('172.30.33.5', 5000)][0m
[31m2026-08-26 05:00:08.224 ERROR (MainThread) [custom_components.frigate] Error fetching frigate data: [0m
[31m2026-08-26 05:00:12.422 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.camera_hal] Error from stream worker: Stream ended; no additional packets[0m
[31m2026-08-26 05:00:13.225 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:False [Connect call failed ('172.30.33.5', 5000)][0m
[31m2026-08-26 05:00:20.635 ERROR (MainThread) [homeassistant.components.hassio.coordinator] Error fetching hassio data: Error on Supervisor API: System is not ready with state: shutdown[0m
s6-rc: info: service legacy-services: stopping
[33m2026-08-26 05:00:21.183 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities media_player.woonkamer are missing or not currently available[0m
[31m2026-08-26 05:00:21.527 ERROR (MainThread) [homeassistant.components.airthings_ble] Setup of config entry 'Airthings Wave Plus (136828)' for airthings_ble integration cancelled
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/bleak_retry_connector/__init__.py", line 491, in establish_connection
    await client.connect(
    ...<2 lines>...
    )
  File "/usr/local/lib/python3.14/site-packages/habluetooth/wrappers.py", line 439, in connect
    wrapped_backend = self._async_get_best_available_backend_and_device(manager)
  File "/usr/local/lib/python3.14/site-packages/habluetooth/wrappers.py", line 672, in _async_get_best_available_backend_and_device
    raise BleakError(msg)
bleak.exc.BleakError: No backend with an available connection slot that can reach address 74:D2:85:05:8A:70 was found: in connectable history; 1 scanner(s) registered, 1 scanning, 1 connectable; last advertisement 17s ago via hci0 (00:E0:4C:23:99:87)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airthings_ble/__init__.py", line 17, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in async_config_entry_first_refresh
    await self._async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 351, in _async_config_entry_first_refresh
    await self._async_refresh(
    ...<3 lines>...
    )
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 435, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airthings_ble/coordinator.py", line 105, in _async_update_data
    data = await self.airthings.update_device(self.ble_device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/airthings_ble/parser.py", line 527, in update_device
    return await self._update_device(ble_device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/airthings_ble/parser.py", line 546, in _update_device
    await establish_connection(  # pylint: disable=line-too-long
    ...<6 lines>...
    )
  File "/usr/local/lib/python3.14/site-packages/bleak_retry_connector/__init__.py", line 593, in establish_connection
    await wait_for_disconnect(device, backoff_time)
  File "/usr/local/lib/python3.14/site-packages/bleak_retry_connector/bluez.py", line 443, in wait_for_disconnect
    await wait_for_device_to_reappear(device, min_wait_time)
  File "/usr/local/lib/python3.14/site-packages/bleak_retry_connector/bluez.py", line 377, in wait_for_device_to_reappear
    await asyncio.sleep(REAPPEAR_WAIT_INTERVAL)
  File "/usr/local/lib/python3.14/asyncio/tasks.py", line 704, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Interrupted by interrupt context manager[0m
Searching for "Drive" by R.E.M....
Searching for "Drive" by R.E.M....
Done.
Done.
Searching for "Teardrop" by Massive Attack...
Searching for "Teardrop" by Massive Attack...
Done.
Done.
Searching for "Pablo's Blues" by Gare Du Nord...
Searching for "Pablo's Blues" by Gare Du Nord...
Done.
Done.
Searching for "The Promise" by Tracy Chapman...
Searching for "The Promise" by Tracy Chapman...
Done.
Done.
Searching for "Protection" by Massive Attack...
Searching for "Protection" by Massive Attack...
Done.
Done.
Searching for "I Need My Girl" by The National...
Searching for "I Need My Girl" by The National...
Done.
Done.
Searching for "Sweet Disposition" by The Temper Trap...
Searching for "Sweet Disposition" by The Temper Trap...
Done.
Done.
Searching for "Heaven Help" by Lenny Kravitz...
Searching for "Heaven Help" by Lenny Kravitz...
Done.
Done.
Searching for "Motherland" by Natalie Merchant...
Searching for "Motherland" by Natalie Merchant...
Done.
Done.
Searching for "Into My Arms" by Nick Cave & The Bad Seeds...
Searching for "Into My Arms" by Nick Cave & The Bad Seeds...
Done.
Done.
Searching for "Listen" by Room Eleven...
Searching for "Listen" by Room Eleven...
Done.
Done.
Searching for "Streets of Philadelphia" by Bruce Springsteen...
Searching for "Streets of Philadelphia - Single Edit" by Bruce Springsteen...
No results found for: 'Streets of Philadelphia - Single Edit Bruce Springsteen'
Done.
Searching for "Where's My Love - Acoustic" by SYML...
Searching for "Where's My Love - Acoustic" by SYML...
Done.
Done.
Searching for "I Follow Rivers" by Triggerfinger...
Searching for "I Follow Rivers - Bonus Track - Live @ Giel Vara/3fm" by Triggerfinger...
No results found for: 'I Follow Rivers - Bonus Track - Live @ Giel Vara/3fm Triggerfinger'
Done.
[03:00:37] INFO: [32mHome Assistant Core finish process exit code 0[0m
[03:00:37] INFO: [32mHome Assistant Core service shutdown[0m
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: warning: service s6rc-oneshot-runner is marked as essential, not stopping it
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
[33m2026-08-26 05:04:03.699 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pet_marvel which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.705 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solcast_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.710 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.714 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration climate_group which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.719 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration genius_lyrics which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.723 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zonneplan_one which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.727 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.733 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration openplantbook which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.738 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zendure_ha which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.743 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frank_energie which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.749 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration plant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.754 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.758 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tplink_deco which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 05:04:03.762 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[31m2026-08-26 05:04:22.168 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up statistics platform for sensor: an integer is required
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 496, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/statistics/sensor.py", line 635, in async_setup_entry
    StatisticsSensor(
    ~~~~~~~~~~~~~~~~^
        hass=hass,
        ^^^^^^^^^^
    ...<8 lines>...
        percentile=int(entry.options[CONF_PERCENTILE]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/statistics/sensor.py", line 694, in __init__
    self.states: deque[float | bool] = deque(maxlen=samples_max_buffer_size)
                                       ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: an integer is required[0m
[31m2026-08-26 05:04:50.147 ERROR (MainThread) [custom_components.genius_lyrics] No media_player entities to monitor[0m
[31m2026-08-26 05:04:58.902 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:False [Timeout while contacting DNS servers][0m
[33m2026-08-26 05:05:14.041 WARNING (MainThread) [homeassistant.components.todo] Setup of todo platform local_todo is taking over 10 seconds.[0m
[33m2026-08-26 05:05:25.404 WARNING (MainThread) [homeassistant.bootstrap] Waiting for integrations to complete setup: {('holiday', '01JCRVX397PBJK4X2TM3P9TJRH'): 136.661674574, ('zonneplan_one', '01JEG73WBEDSMSZGSVPYFK9MYD'): 136.803048728, ('tapo', 'e7a006fe1023366c36affcf037c81f5a'): 150.319804755, ('tapo', '28bb9168f4d53c7605708119fa91af6b'): 150.500635575, ('tapo', '01JBSAHNZSK1SJFD962WCQRXYQ'): 150.601292429, ('tapo', '01KED4HW5T6KNP9WQH2HZY3DHA'): 150.715065831, ('zha', 'd879fa284a34687997554bb8fe272bfd'): 163.898075042, ('homeassistant_sky_connect', 'd92752204b6bf554f43f53d329ee0e4b'): 163.902757452, ('integration', '01JWS1E1Y5CBGP310EQGGERF0P'): 172.755207919, ('integration', '01JWS1GBY05NRM5VYDF5Q9YRY1'): 172.755849001, ('airthings_ble', '01JF54MZJG3R5QXHYFKABY6Q5K'): 173.044100445, ('xiaomi_ble', 'ae66fa82468e1e7343961eb3ea934a06'): 173.525820546, ('xiaomi_ble', 'f1ce8905e635b381bf8d495ca5863987'): 173.526924503, ('xiaomi_ble', '310d52d3f87e641ad9743cd192fe58c8'): 173.527569668, ('xiaomi_ble', 'fc6924af2490fdc65221e0c092ea4586'): 173.527985876, ('xiaomi_ble', '01JN23Q0WKBXM17RPR3VP51HBA'): 173.528359501, ('template', '0f19c5b56571b3b41bb92567f37a24cc'): 180.79765432, ('template', '7b40e0c9085729de2fc87b256623e09f'): 180.798314944, ('template', 'a9bdfba5c4c593dc2eb9affde8aeb5cc'): 180.798771985, ('template', 'f4e334ce0bcadb642b933cab95a0cf5a'): 180.799161068, ('template', '248e242e8e35c18396dc09ed412c01c9'): 180.799601484, ('template', 'c2dc1e3ab0308ed6f93bb8c5ad2a67f4'): 180.799989984, ('template', '01JBMKSFAKAJ2AE3ZX9PPGXFYY'): 180.8005914, ('template', '01K231KY2KEV3VDEE8T5688A0Y'): 180.801203316, ('template', '01K6BGNEQ6FBJ9GG7BEY9F6Z7R'): 180.801732982, ('template', '01KQZM5968NMT2XBXTGENAK9WS'): 180.802192648}[0m
[33m2026-08-26 05:05:27.129 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform tapo is taking over 10 seconds.[0m
[31m2026-08-26 05:05:27.646 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [0m
[33m2026-08-26 05:05:27.660 WARNING (MainThread) [homeassistant.components.update] Setup of update platform tapo is taking over 10 seconds.[0m
[33m2026-08-26 05:05:27.661 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform tapo is taking over 10 seconds.[0m
[31m2026-08-26 05:05:27.680 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [0m
[31m2026-08-26 05:05:27.681 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [0m
[33m2026-08-26 05:05:27.692 WARNING (MainThread) [homeassistant.components.update] Setup of update platform tapo is taking over 10 seconds.[0m
[33m2026-08-26 05:05:27.692 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform tapo is taking over 10 seconds.[0m
[33m2026-08-26 05:05:27.692 WARNING (MainThread) [homeassistant.components.update] Setup of update platform tapo is taking over 10 seconds.[0m
[33m2026-08-26 05:05:27.693 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform tapo is taking over 10 seconds.[0m
[33m2026-08-26 05:05:27.693 WARNING (MainThread) [homeassistant.components.update] Setup of update platform tapo is taking over 10 seconds.[0m
[31m2026-08-26 05:05:27.715 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [0m
[31m2026-08-26 05:05:27.717 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [0m
[31m2026-08-26 05:05:27.718 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [0m
[31m2026-08-26 05:05:27.719 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [0m
[31m2026-08-26 05:05:27.720 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [0m
[33m2026-08-26 05:05:27.775 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'plant' sets an entity ID with wrong domain: 'plant.ficus_max_soil_moisture'. Expected domain is 'number'. This will stop working in Home Assistant 2027.5.0, please create a bug report at https://github.com/Olen/homeassistant-plant/issues[0m
[33m2026-08-26 05:05:52.296 WARNING (MainThread) [homeassistant.components.sonos] Automatic discovery is working, Sonos hosts in configuration.yaml are not needed[0m
[33m2026-08-26 05:05:52.786 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'homeassistant.util.read_only_dict.ReadOnlyDict object' has no attribute 'media_lyrics' when rendering '{% set group_player = states('input_select.sonos_player') %} {% if trigger.id == 'lyrics' and group_player_name is string and group_player_name in trigger.entity_id %} {{ trigger.to_state.attributes.media_lyrics }} {% elif group_player is string and player is string and player!='' and player!=group_player and this.attributes is defined and this.attributes.lyrics is defined %} {{ this.attributes.lyrics }} {% elif lyrics is defined and lyrics is not none and lyrics.media_lyrics is string %} {{ lyrics.media_lyrics }} {% else %} {{ this.attributes.lyrics }} {% endif %}'[0m



[07:09:18] INFO: [32mHome Assistant Core finish process exit code 0[0m
[07:09:18] INFO: [32mHome Assistant Core service shutdown[0m
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: warning: service s6rc-oneshot-runner is marked as essential, not stopping it
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
[33m2026-08-26 09:09:36.250 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pet_marvel which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.256 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solcast_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.260 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.264 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration climate_group which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.268 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration genius_lyrics which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.271 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zonneplan_one which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.274 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.277 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration openplantbook which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.280 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zendure_ha which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.283 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frank_energie which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.286 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration plant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.289 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.292 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tplink_deco which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2026-08-26 09:09:36.295 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
```

### Other Information

HA by default set a log filter when you want to look at the logging of an integration, why don't I see any logging from the Zendure integration?

**Comment by HomeAssistantPim** [comment]
P.s. As of a few weeks (maybe a little while after upgrading from a old version 1.2.x? to 1.4.3?) I have been suffering from issues where the batteries often become inactive.
At first I suspected my batteries (since the upgrade was earlier), but having seen now this behaviour when restarting HA...
And the fact that the regression is slowly getting worse, becoming more often inactive over several weeks of time.
The integration has become my suspect of no longer operating the solarflow 2400AC properly.

**Comment by matthias0701** [comment]
> P.s. As of a few weeks (maybe a little while after upgrading from a old version 1.2.x? to 1.4.3?) I have been suffering from issues where the batteries often become inactive. At first I suspected my batteries (since the upgrade was earlier), but having seen now this behaviour when restarting HA... And the fact that the regression is slowly getting worse, becoming more often inactive over several weeks of time. The integration has become my suspect of no longer operating the solarflow 2400AC properly.

I can also confirm these inactivity issues since i updated to the latest ZHA version. I can wake up the SF2400AC+ after i restart the ZHA integration. Not really satisfying.

**Comment by matthiashe86** [comment]
same problem here. SF2400AC

**Comment by HomeAssistantPim** [comment]
I also see very weird values for sensor.solarflow_2400_ac_pack_state
While the solarflow is charging I see brief states stating it is discharging
@harrymayr this seems serious...

**Comment by matthias0701** [comment]
Now i can only control the SF2400 when the connection is set to "Cloud". ZENSDK does not work anymore for me, regardless which ZHa Version is installed. I think thery are also some issues on Zendure Cloud site

**Comment by matthiashe86** [comment]
Unfortunately, in my case it’s a hardware fault. The contacts on the first battery are damaged. Once I’ve removed the battery, everything works again.

**Comment by HomeAssistantPim** [comment]
Mine too.
I swapped the top batteries and it is working. 
Not sure if it's related. 
I will get a new battery (again, only 4 months old) and a new solarflow. 
I will try to reproduce this with the current stack configuration to make sure asap.
