### PR TITLE
Fix discharge_bypass interactions with non-SOCFULL devices

### LINKED ISSUE #1302: [Bug] 1.3.0 upgrade: 2400AC not charging any more, many errors logged
### Home Assistant Version

2026.4.4

### Zendure Integration Version

v1.3.0

### Describe the bug

After the 1.3.0 update, my SolarFlow 2400 AC does not charge any more, even if my two Hyper 2000 produce enough power. Maybe it's related to these two errors that are logged multiple times every minute:

### To Reproduce

When updating from a working pre-1.3.0 system to 1.3.0, the above error messages start appearing, and 2400AC does not get charged with the excess power from the two Hyper 2000 any more.

See log extracts below

### Expected Behaviour

* 2400AC gets charged with the excess power from the two Hyper 2000.
* The new errors which get logged every couple of seconds disappear atain.

### What device are you using?

SF2400 AC

### Log Extracts

```shell
Logger: custom_components.zendure_ha.manager
Source: custom_components/zendure_ha/manager.py:414
integration: Zendure Home Assistant Integration ([documentation](https://github.com/zendure/zendure-ha), [issues](https://github.com/zendure/zendure-ha/issues))
First occurred: 12:41:53 PM (33 occurrences)
Last logged: 12:47:07 PM

'ZendureNumber' object has no attribute 'asInt'



Logger: custom_components.zendure_ha.manager
Source: custom_components/zendure_ha/manager.py:415
integration: Zendure Home Assistant Integration ([documentation](https://github.com/zendure/zendure-ha), [issues](https://github.com/zendure/zendure-ha/issues))
First occurred: 12:41:53 PM (33 occurrences)
Last logged: 12:47:07 PM

Traceback (most recent call last): File "/config/custom_components/zendure_ha/manager.py", line 412, in _p1_changed await self.powerChanged(p1, isFast, time) File "/config/custom_components/zendure_ha/manager.py", line 475, in powerChanged await self.power_charge(setpoint, time) File "/config/custom_components/zendure_ha/manager.py", line 565, in power_charge await d.power_charge(-start_pwr - max(0, d.pwr_offgrid) if d.state != DeviceState.SOCFULL else -max(0, d.pwr_offgrid)) File "/config/custom_components/zendure_ha/device.py", line 620, in power_charge return await self.charge(power) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/zendure_ha/device.py", line 741, in charge if power == -SmartMode.POWER_START and self.limitInput.asInt == -SmartMode.POWER_START and self.homeInput.asInt == 0: ^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'ZendureNumber' object has no attribute 'asInt'
```

### Other Information

_No response_

### LINKED ISSUE #1312: Zendure SF2400AC+ remains in standby despite surplus
### Home Assistant Version

2026.4.4

### Zendure Integration Version

1.3.1

### Describe the bug

Hello,

after the update yesterday from 1.2.7-pre4 to 1.3.1 my zendure sf2400AC+ stays in standby although i have pv surplus. Only when i change the the "AC-Input" to a manual value like 150W, the SF2400AC+ wake up and start working / loading / unloading again. I have a debug protocoll. I noticed the error at 09:20 today.

### To Reproduce

-

### Expected Behaviour

-

### What device are you using?

SF2400 AC+

### Log Extracts

```shell

```

### Other Information

[home-assistant_zendure_ha_2026-04-29T07-59-27.862Z.log](https://github.com/user-attachments/files/27194564/home-assistant_zendure_ha_2026-04-29T07-59-27.862Z.log)

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #1302. Probably also fixes #1312, depending on the reporter's setup — same symptom shape. #1304 may sound similar, but is definitely not fixed by this.

## Background

#1151 reported SOCFULL Hypers (bypass forbidden) cycling output to 0W: with the original `setpoint -= self.discharge_bypass`, setpoint could flip sign when home demand was below the SOCFULL bypass solar, sending the manager into `power_charge()` against devices that physically couldn't accept charge.

#1162 fixed it by clamping the result at 0 when `p1 ≥ 0`. This works for the #1151 topology (SOCFULL devices, no other absorber/discharger), but is too coarse for the rest of the configuration space — the clamp now runs whether or not other non-SOCFULL devices are present, and that introduces two new failure modes.

## Regressions introduced by #1162

**Charge-side oscillation.** With SOCFULL Hypers passing solar and a non-SOCFULL absorber (e.g. SolarFlow 2400 AC) trying to take the surplus, the absorber's draw flips P1 slightly positive. The clamp's `max(0, …)` then zeroes setpoint — the manager calls `power_discharge(0)`, which tears down the in-flight charge. ~60–90s cycle, never sustains charging.

<details>
<summary>Log excerpt: charge-side oscillation (one cycle, ~100s)</summary>

```
12:02:10  P1 ======> p1:-403  isFast:False  setpoint:-403W
12:02:10  Charge => setpoint -403W
12:02:10  Power charge SolarFlow 2400 AC => -60     ← ramp starts
12:02:26  P1 ======> p1:-339  isFast:False  setpoint:-398W
12:02:26  Power charge SolarFlow 2400 AC => -398    ← full charge
12:02:33  P1 ======> p1:-115  isFast:True   setpoint:-431W
12:02:33  Power charge SolarFlow 2400 AC => -431
12:02:43  P1 ======> p1:+42   isFast:False  setpoint:0W      ← clamp forces 0
12:02:43  Discharge => setpoint 0W
12:02:43  Power discharge SolarFlow 2400 AC => 0    ← charge torn down
12:02:52  Charge => setpoint -360W
12:02:52  Power charge SolarFlow 2400 AC => 0       ← hysteresis lockout
12:02:59  Charge => setpoint -406W                  ← no power command
12:03:13  Charge => setpoint -405W                  ← no power command
12:03:27  Charge => setpoint -407W                  ← no power command
12:03:41  Charge => setpoint -405W                  ← no power command
12:03:52  Power charge SolarFlow 2400 AC => -60     ← cycle restarts
```

</details>

**Steady-state grid import.** Mirror case: heavy load + SOCFULL Hypers + non-SOCFULL discharger. The subtraction makes setpoint converge to `home − bypass` in steady state, so p1 parks at the SOCFULL solar production amount instead of 0. The non-SOCFULL device could close the gap but is never asked to.

<details>
<summary>Log excerpt: steady-state grid import (~6 ticks)</summary>

```
13:48:32  P1 ======> p1:374  setpoint:1722W  stored:367W
13:48:32  Power discharge SolarFlow 2400 AC => 790
13:48:32  Power discharge Hyper 2000 SE     => 466
13:48:32  Power discharge Hyper 2000 SW     => 471
13:48:41  P1 ======> p1:394  setpoint:1756W  stored:369W
13:48:52  P1 ======> p1:391  setpoint:1783W  stored:370W
13:49:04  P1 ======> p1:390  setpoint:1815W  stored:367W
13:49:15  P1 ======> p1:386  setpoint:1842W  stored:368W
```

p1 hovers at ~+385W while setpoint slowly climbs — the system is converging to `p1 = bypass` rather than `p1 = 0`. The `stored:367W` reading is dominated by the two SOCFULL Hypers' solar passthrough, so `bypass ≈ 367W ≈ p1`.

</details>

## Fix

Split the clamp by topology and gate the discharge-side teardown of in-flight charges:

1. **`discharge_bypass` becomes three-branched** in `manager.py`:
   - charge target present → subtract fully, let setpoint go negative so the absorber tracks the surplus.
   - only SOCFULL devices in discharge (#1151's exact topology) → floor at 0 when `p1 ≥ 0`. Identical to today's behavior.
   - non-SOCFULL discharger present → don't subtract; the non-SOCFULL device can absorb the deficit.

2. **Gate the "stop charging devices" loop** at the top of `power_discharge` on `setpoint > SmartMode.POWER_START`. Without this, even with (1) in place a small positive setpoint during the absorber's ramp-up still calls into `power_discharge`, which would unconditionally tear the charge down. Aligns with the threshold the rest of the function already uses to gate `dev_start`.

## Behavior

| scenario | branch hit | result |
|---|---|---|
| #1151 (SOCFULL only, no absorber) | `elif` | identical to today |
| Charge + SOCFULL bypass + non-SOCFULL absorber | `if` | clamp subtracts; setpoint allowed < 0 |
| Discharge + SOCFULL + non-SOCFULL discharger | clamp skipped | converges to p1 ≈ 0 |
| Pure non-SOCFULL discharge | outer cond. false | unchanged |

Reproduced on 2× Hyper 2000 + 1× SolarFlow 2400 AC: no more charge oscillation, p1 converges to ±5W under heavy load, no regression on transient swings.

## Not addressed

The residual issue @Herr-Frodo flagged on #1162 ("AC output stucks at value of POWER_START from constant.py per device") is in a separate code path in the discharge distribution loop (`pwr_low` accounting / per-device clamping) and is unaffected by this PR. #1151's exact topology is left bit-for-bit unchanged.

### CODE REVIEW

**Comment by FireSon** [comment]
@ahocevar  Thanks for the PR! At this moment there are 3 different PR's handling gridReverse=forbidden. They all solve different parts if I understand it correctly. 
#1296 (zaubara) — fixes how discharge_bypass is accumulated (don't accumulate for forbidden devices)
#1318 (ahocevar) — fixes how discharge_bypass is consumed in the setpoint calculation
#1330 (ahocevar) — fixes how forbidden devices affect dev_start and pwr_low hysteresis in power_discharge

I would like to keep things as generic as possible, so no SF2400 specials in the manager. But maybe I am too quick to judge since the cause and effect is not totally clear to me. (I do not have solar panels connected to my SF2400) Can you create a small functional design explaining why and what and where a change is necessary? 
That would be great!
Thanks

**Comment by ahocevar** [comment]
Closing in favor of #1352.
